/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jugador_buscaminas;

import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javafx.embed.swing.JFXPanel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    int TamañoDeMatriz = 30;
    int medidaDePantalla = (TamañoDeMatriz * 20);
    
    public Pantalla() {
        
        initComponents();
        setVisible(true);
        setSize(medidaDePantalla, medidaDePantalla);
        setTitle("no sirvio");
        setResizable(false);
       
        addMouseListener(new MouseListener() {
            
            public void mouseReleased(MouseEvent arg) {
                //Si estamos jugando
                    //Obtiene fila y columna pulsada
                    int f=(arg.getY()-10)/20;
                    int c=arg.getX()/20;
                    
                    System.out.println(arg.getX()+" .. "+arg.getY());
                    System.out.println((arg.getY())/20 +" :--: " + arg.getX()/20);
                    if (arg.getButton()==MouseEvent.BUTTON1){
                        System.out.println(f+" <---> "+c);
                    }else if (arg.getButton()==MouseEvent.BUTTON3){
                       System.out.println(f+" <-|||-> "+c);
                    }
                
                repaint();
            }
            
            public void mousePressed(MouseEvent arg0) {}
            public void mouseClicked(MouseEvent e) {}
            public void mouseExited(MouseEvent arg0) {}
            public void mouseEntered(MouseEvent arg0) {}
        });
        
        addWindowListener(new WindowListener() {
            public void windowClosing(WindowEvent arg0) {
                System.exit(0);
            }
            public void windowOpened(WindowEvent arg0) {}
            public void windowIconified(WindowEvent arg0) {}
            public void windowDeiconified(WindowEvent arg0) {}
            public void windowDeactivated(WindowEvent arg0) {}
            public void windowClosed(WindowEvent arg0) {}
            public void windowActivated(WindowEvent arg0) {}
        });
        
    }
    JButton boton;
    JPanel panel;  
    
    public void agregarBotones(){
        Pantalla tablero = new Pantalla();
        tablero.setVisible(true);
        tablero.setSize(medidaDePantalla,medidaDePantalla);
        tablero.setTitle("Buscaminas");
        tablero.setResizable(false);
        
        panel = new JPanel();
        panel.setLayout(new GridLayout(30,30));
    
        for(int i = 0; i < 30; i++){
            boton = new JButton("EVO " +i);
            
            for(int j = 0; j < 30; j++){
                panel.add(boton); 
                System.out.println("llegoqui");
            }
    }
        panel.setVisible(true);
        tablero.add(panel);
        tablero.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setVisible(false);
        setVisible(false);
        agregarBotones();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               new Pantalla().setVisible(true);
                
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
